services:
  - docker

notifications:
  email:
    - team@appwrite.io

script:
  - docker-compose up -d
  - docker-compose exec tests vendor/bin/pint --test
  - docker-compose exec tests vendor/bin/phpstan analyse
  - docker-compose exec tests vendor/bin/phpunit